# Generated by Django 4.1 on 2022-08-28 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_profile_email_verified'),
        ('Sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sports.sport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sports.sport')),
            ],
        ),
    ]
