# Generated by Django 4.1 on 2022-08-29 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_profile_email_verified'),
        ('Sports', '0003_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sports.slot')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sports.sport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.profile')),
            ],
        ),
    ]
